name: Test flow

on:
  workflow_dispatch:

env:
  SOME_VAR: ${{ github.ref_type }}--${{ secrets.env_secret }}--${{ vars.env_var }}

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: |
          echo SOME_VAR = $SOME_VAR
          echo env.SOME_VAR interpolated = ${{ env.SOME_VAR }}
          echo secrets.env_secret = ${{ secrets.env_secret }}
          echo secrets.ENV_SECRET = ${{ secrets.ENV_SECRET }}
          echo vars.env_var = ${{ vars.env_var }}
          echo vars.ENV_VAR = ${{ vars.ENV_VAR }}
