name: Test flow

on:
  workflow_dispatch:

env:
  FIRST_VAR: first var content
  SECOND_VAR: second var content
  SOME_VAR: ${{ github.ref_type }} -- $FIRST_VAR -- $SECOND_VAR -- $THIRD_VAR
  THIRD_VAR: third var content
  
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: |
          echo ${{ github.job }} -> ${{ step.name }}
          echo SOME_VAR = $SOME_VAR
  second:
    runs-on: ubuntu-latest
    steps:
      - name: Second step
        env:
          SOME_VAR: value redefined on step level
        run: |
          echo ${{ github.job }} -> ${{ step.name }}
          echo SOME_VAR = $SOME_VAR
  third:
    runs-on: ubuntu-latest
    env:
      SOME_VAR: value redefined on job #3 level
    steps:
      - name: Third step
        run: |
          echo ${{ github.job }} -> ${{ step.name }}
          echo SOME_VAR = $SOME_VAR  
  fourth:
    runs-on: ubuntu-latest
    env:
      SOME_VAR: value redefined on job #4 level
    steps:
      - name: Fourth step
        env:
          SOME_VAR: value redefined on step level of job #4
        run: |
          echo ${{ github.job }} -> ${{ step.name }}
          echo SOME_VAR = $SOME_VAR
  fifth:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
